// Generated by utils/fixspec-gen-fields. Do not edit.
//
// One HFFIX_REGISTER_GROUP per repeating group; maps NoXxx to its
// delimiter (first field) for compile-time dispatch via reader.group<NoXxx>().

#pragma once

#include <hffix.hpp>

HFFIX_REGISTER_GROUP(NoAdditionalTermBondRefs, AdditionalTermBondSecurityID);
HFFIX_REGISTER_GROUP(NoAdditionalTerms, AdditionalTermConditionPrecedentBondIndicator);
HFFIX_REGISTER_GROUP(NoAffectedMarketSegments, AffectedMarketSegmentID);
HFFIX_REGISTER_GROUP(NoAffectedOrders, AffectedOrigClOrdID);
HFFIX_REGISTER_GROUP(NoAllocCommissions, AllocCommissionAmount);
HFFIX_REGISTER_GROUP(NoAllocRegulatoryTradeIDs, AllocRegulatoryTradeID);
HFFIX_REGISTER_GROUP(NoAllocs, AllocAccount);
HFFIX_REGISTER_GROUP(NoAltMDSource, AltMDSourceID);
HFFIX_REGISTER_GROUP(NoApplIDs, RefApplID);
HFFIX_REGISTER_GROUP(NoAsgnReqs, NoPartyIDs);
HFFIX_REGISTER_GROUP(NoAssetAttributes, AssetAttributeType);
HFFIX_REGISTER_GROUP(NoAttachmentKeywords, AttachmentKeyword);
HFFIX_REGISTER_GROUP(NoAttachments, AttachmentName);
HFFIX_REGISTER_GROUP(NoAuctionTypeRules, AuctionType);
// NoBidComponents: first-tag conflicts across contexts (messages/components).
//   ListID                      (in BidCompReqGrp)
//   Commission                  (in BidCompRspGrp)
// Compile-time dispatch picks the first-seen (ListID).
// For other contexts (messages/components), use reader.group(tag::NoBidComponents, tag::<delimiter>) runtime overload.
HFFIX_REGISTER_GROUP(NoBidComponents, ListID);
HFFIX_REGISTER_GROUP(NoBidDescriptors, BidDescriptorType);
HFFIX_REGISTER_GROUP(NoBusinessCenters, BusinessCenter);
HFFIX_REGISTER_GROUP(NoCapacities, OrderCapacity);
HFFIX_REGISTER_GROUP(NoCashSettlDateBusinessCenters, CashSettlDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoCashSettlDealers, CashSettlDealer);
HFFIX_REGISTER_GROUP(NoCashSettlTerms, CashSettlCurrency);
HFFIX_REGISTER_GROUP(NoClearingAccountTypes, ClearingAccountType);
HFFIX_REGISTER_GROUP(NoClearingInstructions, ClearingInstruction);
HFFIX_REGISTER_GROUP(NoClearingPriceParameters, BusinessDayType);
HFFIX_REGISTER_GROUP(NoCollInquiryQualifier, CollInquiryQualifier);
HFFIX_REGISTER_GROUP(NoCollateralAmounts, CurrentCollateralAmount);
HFFIX_REGISTER_GROUP(NoCollateralReinvestments, CollateralReinvestmentType);
HFFIX_REGISTER_GROUP(NoCommissions, CommissionAmount);
HFFIX_REGISTER_GROUP(NoCompIDs, RefCompID);
HFFIX_REGISTER_GROUP(NoComplexEventAveragingObservations, ComplexEventAveragingObservationNumber);
HFFIX_REGISTER_GROUP(NoComplexEventCreditEventQualifiers, ComplexEventCreditEventQualifier);
HFFIX_REGISTER_GROUP(NoComplexEventCreditEventSources, ComplexEventCreditEventSource);
HFFIX_REGISTER_GROUP(NoComplexEventCreditEvents, ComplexEventCreditEventType);
HFFIX_REGISTER_GROUP(NoComplexEventDateBusinessCenters, ComplexEventDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoComplexEventDates, ComplexEventStartDate);
HFFIX_REGISTER_GROUP(NoComplexEventPeriodDateTimes, ComplexEventPeriodDate);
HFFIX_REGISTER_GROUP(NoComplexEventPeriods, ComplexEventPeriodType);
HFFIX_REGISTER_GROUP(NoComplexEventRateSources, ComplexEventRateSource);
HFFIX_REGISTER_GROUP(NoComplexEventSchedules, ComplexEventScheduleStartDate);
HFFIX_REGISTER_GROUP(NoComplexEventTimes, ComplexEventStartTime);
HFFIX_REGISTER_GROUP(NoComplexEvents, ComplexEventType);
HFFIX_REGISTER_GROUP(NoContAmts, ContAmtType);
HFFIX_REGISTER_GROUP(NoContraBrokers, ContraBroker);
HFFIX_REGISTER_GROUP(NoContractualDefinitions, ContractualDefinition);
HFFIX_REGISTER_GROUP(NoContractualMatrices, ContractualMatrixSource);
HFFIX_REGISTER_GROUP(NoCrossLegs, LegRefID);
HFFIX_REGISTER_GROUP(NoDates, TradeDate);
HFFIX_REGISTER_GROUP(NoDeliveryScheduleSettlDays, DeliveryScheduleSettlDay);
HFFIX_REGISTER_GROUP(NoDeliveryScheduleSettlTimes, DeliveryScheduleSettlStart);
HFFIX_REGISTER_GROUP(NoDeliverySchedules, DeliveryScheduleType);
HFFIX_REGISTER_GROUP(NoDeliveryStreamCommoditySources, DeliveryStreamCommoditySource);
HFFIX_REGISTER_GROUP(NoDeliveryStreamCycles, DeliveryStreamCycleDesc);
HFFIX_REGISTER_GROUP(NoDerivativeEvents, DerivativeEventType);
HFFIX_REGISTER_GROUP(NoDerivativeInstrAttrib, DerivativeInstrAttribType);
HFFIX_REGISTER_GROUP(NoDerivativeInstrumentParties, DerivativeInstrumentPartyID);
HFFIX_REGISTER_GROUP(NoDerivativeInstrumentPartySubIDs, DerivativeInstrumentPartySubID);
HFFIX_REGISTER_GROUP(NoDerivativeSecurityAltID, DerivativeSecurityAltID);
HFFIX_REGISTER_GROUP(NoDisclosureInstructions, DisclosureType);
HFFIX_REGISTER_GROUP(NoDistribInsts, DistribPaymentMethod);
HFFIX_REGISTER_GROUP(NoDividendAccrualPaymentDateBusinessCenters,
                     DividendAccrualPaymentDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoDividendFXTriggerDateBusinessCenters, DividendFXTriggerDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoDividendPeriodBusinessCenters, DividendPeriodBusinessCenter);
HFFIX_REGISTER_GROUP(NoDividendPeriods, DividendPeriodSequence);
HFFIX_REGISTER_GROUP(NoDlvyInst, SettlInstSource);
HFFIX_REGISTER_GROUP(NoEntitlementAttrib, EntitlementAttribType);
HFFIX_REGISTER_GROUP(NoEntitlementTypes, EntitlementType);
HFFIX_REGISTER_GROUP(NoEntitlements, EntitlementIndicator);
HFFIX_REGISTER_GROUP(NoEvents, EventType);
HFFIX_REGISTER_GROUP(NoExecInstRules, ExecInstValue);
// NoExecs: first-tag conflicts across contexts (messages/components).
//   LastQty                     (in ExecAllocGrp, ExecutionAggregationGrp)
//   ExecID                      (in ExecCollGrp)
// Compile-time dispatch picks the first-seen (LastQty).
// For other contexts (messages/components), use reader.group(tag::NoExecs, tag::<delimiter>) runtime overload.
HFFIX_REGISTER_GROUP(NoExecs, LastQty);
HFFIX_REGISTER_GROUP(NoExpiration, ExpirationQtyType);
HFFIX_REGISTER_GROUP(NoExtraordinaryEvents, ExtraordinaryEventType);
HFFIX_REGISTER_GROUP(NoFills, FillExecID);
HFFIX_REGISTER_GROUP(NoFinancingTermSupplements, FinancingTermSupplementDesc);
HFFIX_REGISTER_GROUP(NoFlexProductEligibilities, FlexProductEligibilityIndicator);
HFFIX_REGISTER_GROUP(NoFundingSources, FundingSource);
HFFIX_REGISTER_GROUP(NoHops, HopCompID);
HFFIX_REGISTER_GROUP(NoIOIQualifiers, IOIQualifier);
HFFIX_REGISTER_GROUP(NoIndexRollMonths, IndexRollMonth);
HFFIX_REGISTER_GROUP(NoInstrAttrib, InstrAttribType);
HFFIX_REGISTER_GROUP(NoInstrmtMatchSides, Symbol);
HFFIX_REGISTER_GROUP(NoInstrumentParties, InstrumentPartyID);
HFFIX_REGISTER_GROUP(NoInstrumentPartySubIDs, InstrumentPartySubID);
HFFIX_REGISTER_GROUP(NoInstrumentScopeSecurityAltID, InstrumentScopeSecurityAltID);
HFFIX_REGISTER_GROUP(NoInstrumentScopes, InstrumentScopeOperator);
HFFIX_REGISTER_GROUP(NoLegAdditionalTermBondRefs, LegAdditionalTermBondSecurityID);
HFFIX_REGISTER_GROUP(NoLegAdditionalTerms, LegAdditionalTermConditionPrecedentBondIndicator);
HFFIX_REGISTER_GROUP(NoLegAllocs, LegAllocAccount);
HFFIX_REGISTER_GROUP(NoLegAssetAttributes, LegAssetAttributeType);
HFFIX_REGISTER_GROUP(NoLegBusinessCenters, LegBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegCashSettlDateBusinessCenters, LegCashSettlDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegCashSettlDealers, LegCashSettlDealer);
HFFIX_REGISTER_GROUP(NoLegCashSettlTerms, LegCashSettlCurrency);
HFFIX_REGISTER_GROUP(NoLegComplexEventAveragingObservations,
                     LegComplexEventAveragingObservationNumber);
HFFIX_REGISTER_GROUP(NoLegComplexEventCreditEventQualifiers, LegComplexEventCreditEventQualifier);
HFFIX_REGISTER_GROUP(NoLegComplexEventCreditEventSources, LegComplexEventCreditEventSource);
HFFIX_REGISTER_GROUP(NoLegComplexEventCreditEvents, LegComplexEventCreditEventType);
HFFIX_REGISTER_GROUP(NoLegComplexEventDateBusinessCenters, LegComplexEventDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegComplexEventDates, LegComplexEventStartDate);
HFFIX_REGISTER_GROUP(NoLegComplexEventPeriodDateTimes, LegComplexEventPeriodDate);
HFFIX_REGISTER_GROUP(NoLegComplexEventPeriods, LegComplexEventPeriodType);
HFFIX_REGISTER_GROUP(NoLegComplexEventRateSources, LegComplexEventRateSource);
HFFIX_REGISTER_GROUP(NoLegComplexEventSchedules, LegComplexEventScheduleStartDate);
HFFIX_REGISTER_GROUP(NoLegComplexEventTimes, LegComplexEventStartTime);
HFFIX_REGISTER_GROUP(NoLegComplexEvents, LegComplexEventType);
HFFIX_REGISTER_GROUP(NoLegContractualDefinitions, LegContractualDefinition);
HFFIX_REGISTER_GROUP(NoLegContractualMatrices, LegContractualMatrixSource);
HFFIX_REGISTER_GROUP(NoLegDeliveryScheduleSettlDays, LegDeliveryScheduleSettlDay);
HFFIX_REGISTER_GROUP(NoLegDeliveryScheduleSettlTimes, LegDeliveryScheduleSettlStart);
HFFIX_REGISTER_GROUP(NoLegDeliverySchedules, LegDeliveryScheduleType);
HFFIX_REGISTER_GROUP(NoLegDeliveryStreamCommoditySources, LegDeliveryStreamCommoditySource);
HFFIX_REGISTER_GROUP(NoLegDeliveryStreamCycles, LegDeliveryStreamCycleDesc);
HFFIX_REGISTER_GROUP(NoLegDividendAccrualPaymentDateBusinessCenters,
                     LegDividendAccrualPaymentDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegDividendFXTriggerDateBusinessCenters,
                     LegDividendFXTriggerDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegDividendPeriodBusinessCenters, LegDividendPeriodBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegDividendPeriods, LegDividendPeriodSequence);
HFFIX_REGISTER_GROUP(NoLegEvents, LegEventType);
HFFIX_REGISTER_GROUP(NoLegExecs, LegRefID);
HFFIX_REGISTER_GROUP(NoLegExtraordinaryEvents, LegExtraordinaryEventType);
HFFIX_REGISTER_GROUP(NoLegFinancingTermSupplements, LegFinancingTermSupplementDesc);
HFFIX_REGISTER_GROUP(NoLegInstrumentParties, LegInstrumentPartyID);
HFFIX_REGISTER_GROUP(NoLegInstrumentPartySubIDs, LegInstrumentPartySubID);
HFFIX_REGISTER_GROUP(NoLegMarketDisruptionEvents, LegMarketDisruptionEvent);
HFFIX_REGISTER_GROUP(NoLegMarketDisruptionFallbackReferencePrices,
                     LegMarketDisruptionFallbackUnderlierType);
HFFIX_REGISTER_GROUP(NoLegMarketDisruptionFallbacks, LegMarketDisruptionFallbackType);
HFFIX_REGISTER_GROUP(NoLegNonDeliverableFixingDates, LegNonDeliverableFixingDate);
HFFIX_REGISTER_GROUP(NoLegOptionExerciseBusinessCenters, LegOptionExerciseBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegOptionExerciseDates, LegOptionExerciseDate);
HFFIX_REGISTER_GROUP(NoLegOptionExerciseExpirationDateBusinessCenters,
                     LegOptionExerciseExpirationDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegOptionExerciseExpirationDates, LegOptionExerciseExpirationDate);
HFFIX_REGISTER_GROUP(NoLegPaymentScheduleFixingDateBusinessCenters,
                     LegPaymentScheduleFixingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegPaymentScheduleFixingDays, LegPaymentScheduleFixingDayOfWeek);
HFFIX_REGISTER_GROUP(NoLegPaymentScheduleInterimExchangeDateBusinessCenters,
                     LegPaymentScheduleInterimExchangeDatesBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegPaymentScheduleRateSources, LegPaymentScheduleRateSource);
HFFIX_REGISTER_GROUP(NoLegPaymentSchedules, LegPaymentScheduleType);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamCompoundingDates, LegPaymentStreamCompoundingDate);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamCompoundingDatesBusinessCenters,
                     LegPaymentStreamCompoundingDatesBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamFixingDateBusinessCenters,
                     LegPaymentStreamFixingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamFixingDates, LegPaymentStreamFixingDate);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamFormulas, LegPaymentStreamFormulaLength);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamInitialFixingDateBusinessCenters,
                     LegPaymentStreamInitialFixingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamNonDeliverableFixingDateBusinessCenters,
                     LegPaymentStreamNonDeliverableFixingDatesBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamPaymentDateBusinessCenters,
                     LegPaymentStreamPaymentDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamPaymentDates, LegPaymentStreamPaymentDate);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamPricingBusinessCenters, LegPaymentStreamPricingBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamPricingDates, LegPaymentStreamPricingDate);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamPricingDays, LegPaymentStreamPricingDayOfWeek);
HFFIX_REGISTER_GROUP(NoLegPaymentStreamResetDateBusinessCenters,
                     LegPaymentStreamResetDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegPaymentStubEndDateBusinessCenters, LegPaymentStubEndDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegPaymentStubStartDateBusinessCenters, LegPaymentStubStartDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegPaymentStubs, LegPaymentStubType);
HFFIX_REGISTER_GROUP(NoLegPhysicalSettlDeliverableObligations,
                     LegPhysicalSettlDeliverableObligationType);
HFFIX_REGISTER_GROUP(NoLegPhysicalSettlTerms, NoLegPhysicalSettlDeliverableObligations);
HFFIX_REGISTER_GROUP(NoLegPosAmt, LegPosAmt);
HFFIX_REGISTER_GROUP(NoLegPricingDateBusinessCenters, LegPricingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegProtectionTermEventNewsSources, LegProtectionTermEventNewsSource);
HFFIX_REGISTER_GROUP(NoLegProtectionTermEventQualifiers, LegProtectionTermEventQualifier);
HFFIX_REGISTER_GROUP(NoLegProtectionTermEvents, LegProtectionTermEventType);
HFFIX_REGISTER_GROUP(NoLegProtectionTermObligations, LegProtectionTermObligationType);
HFFIX_REGISTER_GROUP(NoLegProtectionTerms, LegProtectionTermNotional);
HFFIX_REGISTER_GROUP(NoLegProvisionCashSettlPaymentDateBusinessCenters,
                     LegProvisionCashSettlPaymentDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegProvisionCashSettlPaymentDates, LegProvisionCashSettlPaymentDate);
HFFIX_REGISTER_GROUP(NoLegProvisionCashSettlValueDateBusinessCenters,
                     LegProvisionCashSettlValueDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegProvisionDateBusinessCenters, LegProvisionDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegProvisionOptionExerciseBusinessCenters,
                     LegProvisionOptionExerciseBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegProvisionOptionExerciseFixedDates, LegProvisionOptionExerciseFixedDate);
HFFIX_REGISTER_GROUP(NoLegProvisionOptionExpirationDateBusinessCenters,
                     LegProvisionOptionExpirationDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegProvisionOptionRelevantUnderlyingDateBusinessCenters,
                     LegProvisionOptionRelevantUnderlyingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegProvisionPartyIDs, LegProvisionPartyID);
HFFIX_REGISTER_GROUP(NoLegProvisionPartySubIDs, LegProvisionPartySubID);
HFFIX_REGISTER_GROUP(NoLegProvisions, LegProvisionType);
HFFIX_REGISTER_GROUP(NoLegReturnRateDates, LegReturnRateDateMode);
HFFIX_REGISTER_GROUP(NoLegReturnRateFXConversions, LegReturnRateFXCurrencySymbol);
HFFIX_REGISTER_GROUP(NoLegReturnRateInformationSources, LegReturnRateInformationSource);
HFFIX_REGISTER_GROUP(NoLegReturnRatePrices, LegReturnRatePriceBasis);
HFFIX_REGISTER_GROUP(NoLegReturnRateValuationDateBusinessCenters,
                     LegReturnRateValuationDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegReturnRateValuationDates, LegReturnRateValuationDate);
HFFIX_REGISTER_GROUP(NoLegReturnRates, LegReturnRatePriceSequence);
HFFIX_REGISTER_GROUP(NoLegSecondaryAssetClasses, LegSecondaryAssetClass);
HFFIX_REGISTER_GROUP(NoLegSecurityAltID, LegSecurityAltID);
HFFIX_REGISTER_GROUP(NoLegSettlMethodElectionDateBusinessCenters,
                     LegSettlMethodElectionDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegSettlRateFallbacks, LegSettlRatePostponementMaximumDays);
HFFIX_REGISTER_GROUP(NoLegStipulations, LegStipulationType);
HFFIX_REGISTER_GROUP(NoLegStreamAssetAttributes, LegStreamAssetAttributeType);
HFFIX_REGISTER_GROUP(NoLegStreamCalculationPeriodBusinessCenters,
                     LegStreamCalculationPeriodBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegStreamCalculationPeriodDates, LegStreamCalculationPeriodDate);
HFFIX_REGISTER_GROUP(NoLegStreamCommodityAltIDs, LegStreamCommodityAltID);
HFFIX_REGISTER_GROUP(NoLegStreamCommodityDataSources, LegStreamCommodityDataSourceID);
HFFIX_REGISTER_GROUP(NoLegStreamCommoditySettlBusinessCenters, LegStreamCommoditySettlBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegStreamCommoditySettlDays, LegStreamCommoditySettlDay);
HFFIX_REGISTER_GROUP(NoLegStreamCommoditySettlPeriods, LegStreamCommoditySettlCountry);
HFFIX_REGISTER_GROUP(NoLegStreamCommoditySettlTimes, LegStreamCommoditySettlStart);
HFFIX_REGISTER_GROUP(NoLegStreamEffectiveDateBusinessCenters, LegStreamEffectiveDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegStreamFirstPeriodStartDateBusinessCenters,
                     LegStreamFirstPeriodStartDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegStreamTerminationDateBusinessCenters,
                     LegStreamTerminationDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoLegStreams, LegStreamType);
HFFIX_REGISTER_GROUP(NoLegs, LegSymbol);
HFFIX_REGISTER_GROUP(NoLimitAmts, LimitAmtType);
HFFIX_REGISTER_GROUP(NoLinesOfText, Text);
HFFIX_REGISTER_GROUP(NoLotTypeRules, LotType);
// NoMDEntries: first-tag conflicts across contexts (messages/components).
//   MDEntryType                 (in MDFullGrp)
//   MDUpdateAction              (in MDIncGrp)
// Compile-time dispatch picks the first-seen (MDEntryType).
// For other contexts (messages/components), use reader.group(tag::NoMDEntries, tag::<delimiter>) runtime overload.
HFFIX_REGISTER_GROUP(NoMDEntries, MDEntryType);
HFFIX_REGISTER_GROUP(NoMDEntryTypes, MDEntryType);
HFFIX_REGISTER_GROUP(NoMDFeedTypes, MDFeedType);
// NoMDStatistics: first-tag conflicts across contexts (messages/components).
//   MDStatisticID               (in MDStatisticReqGrp)
//   MDStatisticType             (in MDStatisticRptGrp)
// Compile-time dispatch picks the first-seen (MDStatisticID).
// For other contexts (messages/components), use reader.group(tag::NoMDStatistics, tag::<delimiter>) runtime overload.
HFFIX_REGISTER_GROUP(NoMDStatistics, MDStatisticID);
HFFIX_REGISTER_GROUP(NoMandatoryClearingJurisdictions, MandatoryClearingJurisdiction);
HFFIX_REGISTER_GROUP(NoMarginAmt, MarginAmt);
HFFIX_REGISTER_GROUP(NoMarginReqmtInqQualifier, MarginReqmtInqQualifier);
HFFIX_REGISTER_GROUP(NoMarketDisruptionEvents, MarketDisruptionEvent);
HFFIX_REGISTER_GROUP(NoMarketDisruptionFallbackReferencePrices,
                     MarketDisruptionFallbackUnderlierType);
HFFIX_REGISTER_GROUP(NoMarketDisruptionFallbacks, MarketDisruptionFallbackType);
HFFIX_REGISTER_GROUP(NoMarketSegments, MarketID);
HFFIX_REGISTER_GROUP(NoMatchExceptions, MatchExceptionType);
HFFIX_REGISTER_GROUP(NoMatchInst, MatchInst);
HFFIX_REGISTER_GROUP(NoMatchRules, MatchAlgorithm);
HFFIX_REGISTER_GROUP(NoMatchingDataPoints, MatchingDataPointIndicator);
HFFIX_REGISTER_GROUP(NoMaturityRules, MaturityRuleID);
HFFIX_REGISTER_GROUP(NoMiscFeeSubTypes, MiscFeeSubType);
HFFIX_REGISTER_GROUP(NoMiscFees, MiscFeeAmt);
HFFIX_REGISTER_GROUP(NoMsgTypes, RefMsgType);
HFFIX_REGISTER_GROUP(NoNested2PartyIDs, Nested2PartyID);
HFFIX_REGISTER_GROUP(NoNested2PartySubIDs, Nested2PartySubID);
HFFIX_REGISTER_GROUP(NoNested3PartyIDs, Nested3PartyID);
HFFIX_REGISTER_GROUP(NoNested3PartySubIDs, Nested3PartySubID);
HFFIX_REGISTER_GROUP(NoNested4PartyIDs, Nested4PartyID);
HFFIX_REGISTER_GROUP(NoNested4PartySubIDs, Nested4PartySubID);
HFFIX_REGISTER_GROUP(NoNestedInstrAttrib, NestedInstrAttribType);
HFFIX_REGISTER_GROUP(NoNestedPartyIDs, NestedPartyID);
HFFIX_REGISTER_GROUP(NoNestedPartySubIDs, NestedPartySubID);
HFFIX_REGISTER_GROUP(NoNewsRefIDs, NewsRefID);
HFFIX_REGISTER_GROUP(NoNonDeliverableFixingDates, NonDeliverableFixingDate);
HFFIX_REGISTER_GROUP(NoNotAffectedMarketSegments, NotAffectedMarketSegmentID);
HFFIX_REGISTER_GROUP(NoNotAffectedOrders, NotAffOrigClOrdID);
HFFIX_REGISTER_GROUP(NoOfLegUnderlyings, UnderlyingLegSymbol);
HFFIX_REGISTER_GROUP(NoOfSecSizes, MDSecSizeType);
HFFIX_REGISTER_GROUP(NoOptionExerciseBusinessCenters, OptionExerciseBusinessCenter);
HFFIX_REGISTER_GROUP(NoOptionExerciseDates, OptionExerciseDate);
HFFIX_REGISTER_GROUP(NoOptionExerciseExpirationDateBusinessCenters,
                     OptionExerciseExpirationDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoOptionExerciseExpirationDates, OptionExerciseExpirationDate);
HFFIX_REGISTER_GROUP(NoOrdTypeRules, OrdType);
HFFIX_REGISTER_GROUP(NoOrderAttributes, OrderAttributeType);
// NoOrderEntries: first-tag conflicts across contexts (messages/components).
//   OrderEntryAction            (in OrderEntryGrp)
//   OrdStatus                   (in OrderEntryAckGrp)
// Compile-time dispatch picks the first-seen (OrderEntryAction).
// For other contexts (messages/components), use reader.group(tag::NoOrderEntries, tag::<delimiter>) runtime overload.
HFFIX_REGISTER_GROUP(NoOrderEntries, OrderEntryAction);
HFFIX_REGISTER_GROUP(NoOrderEvents, OrderEventType);
// NoOrders: first-tag conflicts across contexts (messages/components).
//   ClOrdID                     (in ListOrdGrp, OrdAllocGrp, OrdListStatGrp, OrderAggregationGrp)
//   RelatedOrderID              (in RelatedOrderGrp)
// Compile-time dispatch picks the first-seen (ClOrdID).
// For other contexts (messages/components), use reader.group(tag::NoOrders, tag::<delimiter>) runtime overload.
HFFIX_REGISTER_GROUP(NoOrders, ClOrdID);
HFFIX_REGISTER_GROUP(NoPartyDetailAltID, PartyDetailAltID);
HFFIX_REGISTER_GROUP(NoPartyDetailAltSubIDs, PartyDetailAltSubID);
HFFIX_REGISTER_GROUP(NoPartyDetailSubIDs, PartyDetailSubID);
HFFIX_REGISTER_GROUP(NoPartyDetails, PartyDetailID);
// NoPartyEntitlements: first-tag conflicts across contexts (messages/components).
//   NoPartyDetails              (in PartyEntitlementGrp)
//   ListUpdateAction            (in PartyEntitlementUpdateGrp, PartyEntitlementAckGrp)
// Compile-time dispatch picks the first-seen (NoPartyDetails).
// For other contexts (messages/components), use reader.group(tag::NoPartyEntitlements, tag::<delimiter>) runtime overload.
HFFIX_REGISTER_GROUP(NoPartyEntitlements, NoPartyDetails);
HFFIX_REGISTER_GROUP(NoPartyIDs, PartyID);
HFFIX_REGISTER_GROUP(NoPartyRelationships, PartyRelationship);
// NoPartyRiskLimits: first-tag conflicts across contexts (messages/components).
//   NoPartyDetails              (in PartyRiskLimitsGrp)
//   ListUpdateAction            (in PartyRiskLimitsUpdateGrp, PartyRiskLimitsAckGrp)
// Compile-time dispatch picks the first-seen (NoPartyDetails).
// For other contexts (messages/components), use reader.group(tag::NoPartyRiskLimits, tag::<delimiter>) runtime overload.
HFFIX_REGISTER_GROUP(NoPartyRiskLimits, NoPartyDetails);
HFFIX_REGISTER_GROUP(NoPartySubIDs, PartySubID);
HFFIX_REGISTER_GROUP(NoPartyUpdates, ListUpdateAction);
HFFIX_REGISTER_GROUP(NoPayCollects, PayCollectType);
HFFIX_REGISTER_GROUP(NoPaymentBusinessCenters, PaymentBusinessCenter);
HFFIX_REGISTER_GROUP(NoPaymentScheduleFixingDateBusinessCenters,
                     PaymentScheduleFixingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoPaymentScheduleFixingDays, PaymentScheduleFixingDayOfWeek);
HFFIX_REGISTER_GROUP(NoPaymentScheduleInterimExchangeDateBusinessCenters,
                     PaymentScheduleInterimExchangeDatesBusinessCenter);
HFFIX_REGISTER_GROUP(NoPaymentScheduleRateSources, PaymentScheduleRateSource);
HFFIX_REGISTER_GROUP(NoPaymentSchedules, PaymentScheduleType);
HFFIX_REGISTER_GROUP(NoPaymentSettlPartyIDs, PaymentSettlPartyID);
HFFIX_REGISTER_GROUP(NoPaymentSettlPartySubIDs, PaymentSettlPartySubID);
HFFIX_REGISTER_GROUP(NoPaymentSettls, PaymentSettlAmount);
HFFIX_REGISTER_GROUP(NoPaymentStreamCompoundingDates, PaymentStreamCompoundingDate);
HFFIX_REGISTER_GROUP(NoPaymentStreamCompoundingDatesBusinessCenters,
                     PaymentStreamCompoundingDatesBusinessCenter);
HFFIX_REGISTER_GROUP(NoPaymentStreamFixingDateBusinessCenters, PaymentStreamFixingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoPaymentStreamFixingDates, PaymentStreamFixingDate);
HFFIX_REGISTER_GROUP(NoPaymentStreamFormulas, PaymentStreamFormulaLength);
HFFIX_REGISTER_GROUP(NoPaymentStreamInitialFixingDateBusinessCenters,
                     PaymentStreamInitialFixingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoPaymentStreamNonDeliverableFixingDatesBusinessCenters,
                     PaymentStreamNonDeliverableFixingDatesBusinessCenter);
HFFIX_REGISTER_GROUP(NoPaymentStreamPaymentDateBusinessCenters,
                     PaymentStreamPaymentDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoPaymentStreamPaymentDates, PaymentStreamPaymentDate);
HFFIX_REGISTER_GROUP(NoPaymentStreamPricingBusinessCenters, PaymentStreamPricingBusinessCenter);
HFFIX_REGISTER_GROUP(NoPaymentStreamPricingDates, PaymentStreamPricingDate);
HFFIX_REGISTER_GROUP(NoPaymentStreamPricingDays, PaymentStreamPricingDayOfWeek);
HFFIX_REGISTER_GROUP(NoPaymentStreamResetDateBusinessCenters, PaymentStreamResetDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoPaymentStubEndDateBusinessCenters, PaymentStubEndDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoPaymentStubStartDateBusinessCenters, PaymentStubStartDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoPaymentStubs, PaymentStubType);
HFFIX_REGISTER_GROUP(NoPayments, PaymentType);
HFFIX_REGISTER_GROUP(NoPhysicalSettlDeliverableObligations, PhysicalSettlDeliverableObligationType);
HFFIX_REGISTER_GROUP(NoPhysicalSettlTerms, NoPhysicalSettlDeliverableObligations);
HFFIX_REGISTER_GROUP(NoPosAmt, PosAmtType);
HFFIX_REGISTER_GROUP(NoPositions, PosType);
HFFIX_REGISTER_GROUP(NoPriceMovementValues, PriceMovementValue);
HFFIX_REGISTER_GROUP(NoPriceMovements, NoPriceMovementValues);
HFFIX_REGISTER_GROUP(NoPriceQualifiers, PriceQualifier);
HFFIX_REGISTER_GROUP(NoPriceRangeRules, StartPriceRange);
HFFIX_REGISTER_GROUP(NoPricingDateBusinessCenters, PricingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoProtectionTermEventNewsSources, ProtectionTermEventNewsSource);
HFFIX_REGISTER_GROUP(NoProtectionTermEventQualifiers, ProtectionTermEventQualifier);
HFFIX_REGISTER_GROUP(NoProtectionTermEvents, ProtectionTermEventType);
HFFIX_REGISTER_GROUP(NoProtectionTermObligations, ProtectionTermObligationType);
HFFIX_REGISTER_GROUP(NoProtectionTerms, ProtectionTermNotional);
HFFIX_REGISTER_GROUP(NoProvisionCashSettlPaymentDateBusinessCenters,
                     ProvisionCashSettlPaymentDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoProvisionCashSettlPaymentDates, ProvisionCashSettlPaymentDate);
HFFIX_REGISTER_GROUP(NoProvisionCashSettlValueDateBusinessCenters,
                     ProvisionCashSettlValueDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoProvisionDateBusinessCenters, ProvisionDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoProvisionOptionExerciseBusinessCenters, ProvisionOptionExerciseBusinessCenter);
HFFIX_REGISTER_GROUP(NoProvisionOptionExerciseFixedDates, ProvisionOptionExerciseFixedDate);
HFFIX_REGISTER_GROUP(NoProvisionOptionExpirationDateBusinessCenters,
                     ProvisionOptionExpirationDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoProvisionOptionRelevantUnderlyingDateBusinessCenters,
                     ProvisionOptionRelevantUnderlyingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoProvisionPartyIDs, ProvisionPartyID);
HFFIX_REGISTER_GROUP(NoProvisionPartySubIDs, ProvisionPartySubID);
HFFIX_REGISTER_GROUP(NoProvisions, ProvisionType);
HFFIX_REGISTER_GROUP(NoQuoteAttributes, QuoteAttributeType);
// NoQuoteEntries: first-tag conflicts across contexts (messages/components).
//   Symbol                      (in QuotCxlEntriesGrp)
//   QuoteEntryID                (in QuotEntryAckGrp, QuotEntryGrp)
// Compile-time dispatch picks the first-seen (Symbol).
// For other contexts (messages/components), use reader.group(tag::NoQuoteEntries, tag::<delimiter>) runtime overload.
HFFIX_REGISTER_GROUP(NoQuoteEntries, Symbol);
HFFIX_REGISTER_GROUP(NoQuoteQualifiers, QuoteQualifier);
HFFIX_REGISTER_GROUP(NoQuoteSets, QuoteSetID);
HFFIX_REGISTER_GROUP(NoQuoteSizeRules, MinBidSize);
HFFIX_REGISTER_GROUP(NoRateSources, NoRateSources);
HFFIX_REGISTER_GROUP(NoReferenceDataDates, ReferenceDataDate);
HFFIX_REGISTER_GROUP(NoRegistDtls, RegistDtls);
HFFIX_REGISTER_GROUP(NoRegulatoryTradeIDs, RegulatoryTradeID);
HFFIX_REGISTER_GROUP(NoRelatedInstruments, RelatedInstrumentType);
HFFIX_REGISTER_GROUP(NoRelatedMarketSegments, RelatedMarketSegmentID);
HFFIX_REGISTER_GROUP(NoRelatedPartyDetailAltID, RelatedPartyDetailAltID);
HFFIX_REGISTER_GROUP(NoRelatedPartyDetailAltSubIDs, RelatedPartyDetailAltSubID);
HFFIX_REGISTER_GROUP(NoRelatedPartyDetailID, RelatedPartyDetailID);
HFFIX_REGISTER_GROUP(NoRelatedPartyDetailSubIDs, RelatedPartyDetailSubID);
HFFIX_REGISTER_GROUP(NoRelatedPositions, RelatedPositionID);
// NoRelatedSym: first-tag conflicts across contexts (messages/components).
//   Symbol                      (in InstrmtGrp, InstrmtMDReqGrp, QuotReqGrp, QuotReqRjctGrp, RelSymDerivSecGrp, RFQReqGrp, SecListGrp, StrmAsgnReqInstrmtGrp, StrmAsgnRptInstrmtGrp, SecMassStatGrp)
//   ListUpdateAction            (in SecLstUpdRelSymGrp, RelSymDerivSecUpdGrp)
// Compile-time dispatch picks the first-seen (Symbol).
// For other contexts (messages/components), use reader.group(tag::NoRelatedSym, tag::<delimiter>) runtime overload.
HFFIX_REGISTER_GROUP(NoRelatedSym, Symbol);
HFFIX_REGISTER_GROUP(NoRelatedTrades, RelatedTradeID);
HFFIX_REGISTER_GROUP(NoRelativeValues, RelativeValueType);
HFFIX_REGISTER_GROUP(NoRequestedPartyRoles, RequestedPartyRole);
HFFIX_REGISTER_GROUP(NoRequestedRiskLimitType, RiskLimitType);
HFFIX_REGISTER_GROUP(NoRequestingPartyIDs, RequestingPartyID);
HFFIX_REGISTER_GROUP(NoRequestingPartySubIDs, RequestingPartySubID);
HFFIX_REGISTER_GROUP(NoReturnRateDates, ReturnRateDateMode);
HFFIX_REGISTER_GROUP(NoReturnRateFXConversions, ReturnRateFXCurrencySymbol);
HFFIX_REGISTER_GROUP(NoReturnRateInformationSources, ReturnRateInformationSource);
HFFIX_REGISTER_GROUP(NoReturnRatePrices, ReturnRatePriceBasis);
HFFIX_REGISTER_GROUP(NoReturnRateValuationDateBusinessCenters, ReturnRateValuationDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoReturnRateValuationDates, ReturnRateValuationDate);
HFFIX_REGISTER_GROUP(NoReturnRates, ReturnRatePriceSequence);
HFFIX_REGISTER_GROUP(NoRiskInstrumentScopes, InstrumentScopeOperator);
HFFIX_REGISTER_GROUP(NoRiskLimitTypes, RiskLimitType);
HFFIX_REGISTER_GROUP(NoRiskLimits, NoRiskLimitTypes);
HFFIX_REGISTER_GROUP(NoRiskWarningLevels, RiskWarningLevelAction);
HFFIX_REGISTER_GROUP(NoRootPartyIDs, RootPartyID);
HFFIX_REGISTER_GROUP(NoRootPartySubIDs, RootPartySubID);
HFFIX_REGISTER_GROUP(NoRoutingIDs, RoutingType);
HFFIX_REGISTER_GROUP(NoSecondaryAssetClasses, SecondaryAssetClass);
HFFIX_REGISTER_GROUP(NoSecurityAltID, SecurityAltID);
HFFIX_REGISTER_GROUP(NoSecurityClassifications, SecurityClassificationReason);
HFFIX_REGISTER_GROUP(NoSecurityTypes, SecurityType);
HFFIX_REGISTER_GROUP(NoSettlDetails, SettlObligSource);
HFFIX_REGISTER_GROUP(NoSettlInst, SettlInstID);
HFFIX_REGISTER_GROUP(NoSettlMethodElectionDateBusinessCenters, SettlMethodElectionDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoSettlOblig, NetGrossInd);
HFFIX_REGISTER_GROUP(NoSettlPartyIDs, SettlPartyID);
HFFIX_REGISTER_GROUP(NoSettlPartySubIDs, SettlPartySubID);
HFFIX_REGISTER_GROUP(NoSettlRateFallbacks, SettlRatePostponementMaximumDays);
HFFIX_REGISTER_GROUP(NoSettlementAmounts, SettlementAmount);
HFFIX_REGISTER_GROUP(NoSideCollateralAmounts, SideCurrentCollateralAmount);
HFFIX_REGISTER_GROUP(NoSideCollateralReinvestments, SideCollateralReinvestmentType);
HFFIX_REGISTER_GROUP(NoSideRegulatoryTradeIDs, SideRegulatoryTradeID);
HFFIX_REGISTER_GROUP(NoSideTrdRegTS, SideTrdRegTimestamp);
HFFIX_REGISTER_GROUP(NoSides, Side);
HFFIX_REGISTER_GROUP(NoStatsIndicators, StatsType);
HFFIX_REGISTER_GROUP(NoStipulations, StipulationType);
HFFIX_REGISTER_GROUP(NoStrategyParameters, StrategyParameterName);
HFFIX_REGISTER_GROUP(NoStreamAssetAttributes, StreamAssetAttributeType);
HFFIX_REGISTER_GROUP(NoStreamCalculationPeriodBusinessCenters, StreamCalculationPeriodBusinessCenter);
HFFIX_REGISTER_GROUP(NoStreamCalculationPeriodDates, StreamCalculationPeriodDate);
HFFIX_REGISTER_GROUP(NoStreamCommodityAltIDs, StreamCommodityAltID);
HFFIX_REGISTER_GROUP(NoStreamCommodityDataSources, StreamCommodityDataSourceID);
HFFIX_REGISTER_GROUP(NoStreamCommoditySettlBusinessCenters, StreamCommoditySettlBusinessCenter);
HFFIX_REGISTER_GROUP(NoStreamCommoditySettlDays, StreamCommoditySettlDay);
HFFIX_REGISTER_GROUP(NoStreamCommoditySettlPeriods, StreamCommoditySettlCountry);
HFFIX_REGISTER_GROUP(NoStreamCommoditySettlTimes, StreamCommoditySettlStart);
HFFIX_REGISTER_GROUP(NoStreamEffectiveDateBusinessCenters, StreamEffectiveDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoStreamFirstPeriodStartDateBusinessCenters,
                     StreamFirstPeriodStartDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoStreamTerminationDateBusinessCenters, StreamTerminationDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoStreams, StreamType);
HFFIX_REGISTER_GROUP(NoStrikeRules, StrikeRuleID);
HFFIX_REGISTER_GROUP(NoStrikes, Symbol);
HFFIX_REGISTER_GROUP(NoTargetMarketSegments, TargetMarketSegmentID);
HFFIX_REGISTER_GROUP(NoTargetPartyIDs, TargetPartyID);
HFFIX_REGISTER_GROUP(NoTargetPartySubIDs, TargetPartySubID);
HFFIX_REGISTER_GROUP(NoThrottleMsgType, ThrottleMsgType);
HFFIX_REGISTER_GROUP(NoThrottles, ThrottleAction);
HFFIX_REGISTER_GROUP(NoTickRules, StartTickPriceRange);
HFFIX_REGISTER_GROUP(NoTimeInForceRules, TimeInForce);
HFFIX_REGISTER_GROUP(NoTradeAllocAmts, TradeAllocAmtType);
HFFIX_REGISTER_GROUP(NoTradePriceConditions, TradePriceCondition);
HFFIX_REGISTER_GROUP(NoTradeQtys, TradeQtyType);
HFFIX_REGISTER_GROUP(NoTrades, TradeReportID);
HFFIX_REGISTER_GROUP(NoTradingSessionRules, TradingSessionID);
HFFIX_REGISTER_GROUP(NoTradingSessions, TradingSessionID);
HFFIX_REGISTER_GROUP(NoTransactionAttributes, TransactionAttributeType);
HFFIX_REGISTER_GROUP(NoTrdMatchSides, Side);
HFFIX_REGISTER_GROUP(NoTrdRegPublications, TrdRegPublicationType);
HFFIX_REGISTER_GROUP(NoTrdRegTimestamps, TrdRegTimestamp);
HFFIX_REGISTER_GROUP(NoTrdRepIndicators, TrdRepPartyRole);
HFFIX_REGISTER_GROUP(NoUnderlyingAdditionalTermBondRefs, UnderlyingAdditionalTermBondSecurityID);
HFFIX_REGISTER_GROUP(NoUnderlyingAdditionalTerms,
                     UnderlyingAdditionalTermConditionPrecedentBondIndicator);
HFFIX_REGISTER_GROUP(NoUnderlyingAmounts, UnderlyingPayAmount);
HFFIX_REGISTER_GROUP(NoUnderlyingAssetAttributes, UnderlyingAssetAttributeType);
HFFIX_REGISTER_GROUP(NoUnderlyingBusinessCenters, UnderlyingBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingCashSettlDateBusinessCenters, UnderlyingCashSettlDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingCashSettlDealers, UnderlyingCashSettlDealer);
HFFIX_REGISTER_GROUP(NoUnderlyingCashSettlTerms, UnderlyingCashSettlCurrency);
HFFIX_REGISTER_GROUP(NoUnderlyingComplexEventAveragingObservations,
                     UnderlyingComplexEventAveragingObservationNumber);
HFFIX_REGISTER_GROUP(NoUnderlyingComplexEventCreditEventQualifiers,
                     UnderlyingComplexEventCreditEventQualifier);
HFFIX_REGISTER_GROUP(NoUnderlyingComplexEventCreditEventSources,
                     UnderlyingComplexEventCreditEventSource);
HFFIX_REGISTER_GROUP(NoUnderlyingComplexEventCreditEvents, UnderlyingComplexEventCreditEventType);
HFFIX_REGISTER_GROUP(NoUnderlyingComplexEventDateBusinessCenters,
                     UnderlyingComplexEventDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingComplexEventDates, UnderlyingComplexEventStartDate);
HFFIX_REGISTER_GROUP(NoUnderlyingComplexEventPeriodDateTimes, UnderlyingComplexEventPeriodDate);
HFFIX_REGISTER_GROUP(NoUnderlyingComplexEventPeriods, UnderlyingComplexEventPeriodType);
HFFIX_REGISTER_GROUP(NoUnderlyingComplexEventRateSources, UnderlyingComplexEventRateSource);
HFFIX_REGISTER_GROUP(NoUnderlyingComplexEventSchedules, UnderlyingComplexEventScheduleStartDate);
HFFIX_REGISTER_GROUP(NoUnderlyingComplexEventTimes, UnderlyingComplexEventStartTime);
HFFIX_REGISTER_GROUP(NoUnderlyingComplexEvents, UnderlyingComplexEventType);
HFFIX_REGISTER_GROUP(NoUnderlyingDeliveryScheduleSettlDays, UnderlyingDeliveryScheduleSettlDay);
HFFIX_REGISTER_GROUP(NoUnderlyingDeliveryScheduleSettlTimes, UnderlyingDeliveryScheduleSettlStart);
HFFIX_REGISTER_GROUP(NoUnderlyingDeliverySchedules, UnderlyingDeliveryScheduleType);
HFFIX_REGISTER_GROUP(NoUnderlyingDeliveryStreamCommoditySources,
                     UnderlyingDeliveryStreamCommoditySource);
HFFIX_REGISTER_GROUP(NoUnderlyingDeliveryStreamCycles, UnderlyingDeliveryStreamCycleDesc);
HFFIX_REGISTER_GROUP(NoUnderlyingDividendAccrualPaymentDateBusinessCenters,
                     UnderlyingDividendAccrualPaymentDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingDividendFXTriggerDateBusinessCenters,
                     UnderlyingDividendFXTriggerDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingDividendPayments, UnderlyingDividendPaymentDate);
HFFIX_REGISTER_GROUP(NoUnderlyingDividendPeriodBusinessCenters,
                     UnderlyingDividendPeriodBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingDividendPeriods, UnderlyingDividendPeriodSequence);
HFFIX_REGISTER_GROUP(NoUnderlyingEvents, UnderlyingEventType);
HFFIX_REGISTER_GROUP(NoUnderlyingExtraordinaryEvents, UnderlyingExtraordinaryEventType);
HFFIX_REGISTER_GROUP(NoUnderlyingLegSecurityAltID, UnderlyingLegSecurityAltID);
HFFIX_REGISTER_GROUP(NoUnderlyingMarketDisruptionEvents, UnderlyingMarketDisruptionEvent);
HFFIX_REGISTER_GROUP(NoUnderlyingMarketDisruptionFallbackReferencePrices,
                     UnderlyingMarketDisruptionFallbackUnderlierType);
HFFIX_REGISTER_GROUP(NoUnderlyingMarketDisruptionFallbacks, UnderlyingMarketDisruptionFallbackType);
HFFIX_REGISTER_GROUP(NoUnderlyingNonDeliverableFixingDates, UnderlyingNonDeliverableFixingDate);
HFFIX_REGISTER_GROUP(NoUnderlyingOptionExerciseBusinessCenters,
                     UnderlyingOptionExerciseBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingOptionExerciseDates, UnderlyingOptionExerciseDate);
HFFIX_REGISTER_GROUP(NoUnderlyingOptionExerciseExpirationDateBusinessCenters,
                     UnderlyingOptionExerciseExpirationDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingOptionExerciseExpirationDates,
                     UnderlyingOptionExerciseExpirationDate);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentScheduleFixingDateBusinessCenters,
                     UnderlyingPaymentScheduleFixingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentScheduleFixingDays, UnderlyingPaymentScheduleFixingDayOfWeek);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentScheduleInterimExchangeDateBusinessCenters,
                     UnderlyingPaymentScheduleInterimExchangeDatesBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentScheduleRateSources, UnderlyingPaymentScheduleRateSource);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentSchedules, UnderlyingPaymentScheduleType);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamCompoundingDates,
                     UnderlyingPaymentStreamCompoundingDate);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamCompoundingDatesBusinessCenters,
                     UnderlyingPaymentStreamCompoundingDatesBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamFixingDateBusinessCenters,
                     UnderlyingPaymentStreamFixingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamFixingDates, UnderlyingPaymentStreamFixingDate);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamFormulas, UnderlyingPaymentStreamFormulaLength);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamInitialFixingDateBusinessCenters,
                     UnderlyingPaymentStreamInitialFixingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamNonDeliverableFixingDatesBizCenters,
                     UnderlyingPaymentStreamNonDeliverableFixingDatesBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamPaymentDateBusinessCenters,
                     UnderlyingPaymentStreamPaymentDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamPaymentDates, UnderlyingPaymentStreamPaymentDate);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamPricingBusinessCenters,
                     UnderlyingPaymentStreamPricingBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamPricingDates, UnderlyingPaymentStreamPricingDate);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamPricingDays, UnderlyingPaymentStreamPricingDayOfWeek);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStreamResetDateBusinessCenters,
                     UnderlyingPaymentStreamResetDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStubEndDateBusinessCenters,
                     UnderlyingPaymentStubEndDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStubStartDateBusinessCenters,
                     UnderlyingPaymentStubStartDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingPaymentStubs, UnderlyingPaymentStubType);
HFFIX_REGISTER_GROUP(NoUnderlyingPhysicalSettlDeliverableObligations,
                     UnderlyingPhysicalSettlDeliverableObligationType);
HFFIX_REGISTER_GROUP(NoUnderlyingPhysicalSettlTerms, NoUnderlyingPhysicalSettlDeliverableObligations);
HFFIX_REGISTER_GROUP(NoUnderlyingPricingDateBusinessCenters, UnderlyingPricingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingProtectionTermEventNewsSources,
                     UnderlyingProtectionTermEventNewsSource);
HFFIX_REGISTER_GROUP(NoUnderlyingProtectionTermEventQualifiers,
                     UnderlyingProtectionTermEventQualifier);
HFFIX_REGISTER_GROUP(NoUnderlyingProtectionTermEvents, UnderlyingProtectionTermEventType);
HFFIX_REGISTER_GROUP(NoUnderlyingProtectionTermObligations, UnderlyingProtectionTermObligationType);
HFFIX_REGISTER_GROUP(NoUnderlyingProtectionTerms, UnderlyingProtectionTermNotional);
HFFIX_REGISTER_GROUP(NoUnderlyingProvisionCashSettlPaymentDateBusinessCenters,
                     UnderlyingProvisionCashSettlPaymentDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingProvisionCashSettlPaymentDates,
                     UnderlyingProvisionCashSettlPaymentDate);
HFFIX_REGISTER_GROUP(NoUnderlyingProvisionCashSettlValueDateBusinessCenters,
                     UnderlyingProvisionCashSettlValueDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingProvisionDateBusinessCenters, UnderlyingProvisionDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingProvisionOptionExerciseBusinessCenters,
                     UnderlyingProvisionOptionExerciseBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingProvisionOptionExerciseFixedDates,
                     UnderlyingProvisionOptionExerciseFixedDate);
HFFIX_REGISTER_GROUP(NoUnderlyingProvisionOptionExpirationDateBusinessCenters,
                     UnderlyingProvisionOptionExpirationDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenters,
                     UnderlyingProvisionOptionRelevantUnderlyingDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingProvisionPartyIDs, UnderlyingProvisionPartyID);
HFFIX_REGISTER_GROUP(NoUnderlyingProvisionPartySubIDs, UnderlyingProvisionPartySubID);
HFFIX_REGISTER_GROUP(NoUnderlyingProvisions, UnderlyingProvisionType);
HFFIX_REGISTER_GROUP(NoUnderlyingRateSpreadSteps, UnderlyingRateSpreadStepDate);
HFFIX_REGISTER_GROUP(NoUnderlyingReturnRateDates, UnderlyingReturnRateDateMode);
HFFIX_REGISTER_GROUP(NoUnderlyingReturnRateFXConversions, UnderlyingReturnRateFXCurrencySymbol);
HFFIX_REGISTER_GROUP(NoUnderlyingReturnRateInformationSources, UnderlyingReturnRateInformationSource);
HFFIX_REGISTER_GROUP(NoUnderlyingReturnRatePrices, UnderlyingReturnRatePriceBasis);
HFFIX_REGISTER_GROUP(NoUnderlyingReturnRateValuationDateBusinessCenters,
                     UnderlyingReturnRateValuationDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingReturnRateValuationDates, UnderlyingReturnRateValuationDate);
HFFIX_REGISTER_GROUP(NoUnderlyingReturnRates, UnderlyingReturnRatePriceSequence);
HFFIX_REGISTER_GROUP(NoUnderlyingSecondaryAssetClasses, UnderlyingSecondaryAssetClass);
HFFIX_REGISTER_GROUP(NoUnderlyingSecurityAltID, UnderlyingSecurityAltID);
HFFIX_REGISTER_GROUP(NoUnderlyingSettlMethodElectionDateBusinessCenters,
                     UnderlyingSettlMethodElectionDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingSettlRateFallbacks, UnderlyingSettlRatePostponementMaximumDays);
HFFIX_REGISTER_GROUP(NoUnderlyingStips, UnderlyingStipType);
HFFIX_REGISTER_GROUP(NoUnderlyingStreamAssetAttributes, UnderlyingStreamAssetAttributeType);
HFFIX_REGISTER_GROUP(NoUnderlyingStreamCalculationPeriodBusinessCenters,
                     UnderlyingStreamCalculationPeriodBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingStreamCalculationPeriodDates, UnderlyingStreamCalculationPeriodDate);
HFFIX_REGISTER_GROUP(NoUnderlyingStreamCommodityAltIDs, UnderlyingStreamCommodityAltID);
HFFIX_REGISTER_GROUP(NoUnderlyingStreamCommodityDataSources, UnderlyingStreamCommodityDataSourceID);
HFFIX_REGISTER_GROUP(NoUnderlyingStreamCommoditySettlBusinessCenters,
                     UnderlyingStreamCommoditySettlBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingStreamCommoditySettlDays, UnderlyingStreamCommoditySettlDay);
HFFIX_REGISTER_GROUP(NoUnderlyingStreamCommoditySettlPeriods, UnderlyingStreamCommoditySettlCountry);
HFFIX_REGISTER_GROUP(NoUnderlyingStreamCommoditySettlTimes, UnderlyingStreamCommoditySettlStart);
HFFIX_REGISTER_GROUP(NoUnderlyingStreamEffectiveDateBusinessCenters,
                     UnderlyingStreamEffectiveDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingStreamFirstPeriodStartDateBusinessCenters,
                     UnderlyingStreamFirstPeriodStartDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingStreamTerminationDateBusinessCenters,
                     UnderlyingStreamTerminationDateBusinessCenter);
HFFIX_REGISTER_GROUP(NoUnderlyingStreams, UnderlyingStreamType);
HFFIX_REGISTER_GROUP(NoUnderlyings, UnderlyingSymbol);
HFFIX_REGISTER_GROUP(NoUndlyInstrumentParties, UnderlyingInstrumentPartyID);
HFFIX_REGISTER_GROUP(NoUndlyInstrumentPartySubIDs, UnderlyingInstrumentPartySubID);
HFFIX_REGISTER_GROUP(NoUsernames, Username);
HFFIX_REGISTER_GROUP(NoValueChecks, ValueCheckType);
